### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details! Exit Code: -1

### ISSUE THREAD

**Issue by Joey-Destroyah** [OpenCubicChunks/CubicWorldGen#112]
modlist:   

CubicChunks
CubicWorldGen
FlansModExtended

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 9/16/20 5:39 PM
Description: Initializing game

java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:549)
	at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:596)
	at net.minecraftforge.registries.GameData.freezeData(GameData.java:249)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:758)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 400234416 bytes (381 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version                    | Source                                          | Signature |
	|:------ |:------------------ |:-------------------------- |:----------------------------------------------- |:--------- |
	| LCHIJA | minecraft          | 1.12.2                     | minecraft.jar                                   | None      |
	| LCHIJA | mcp                | 9.42                       | minecraft.jar                                   | None      |
	| LCHIJA | FML                | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | forge              | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                   | None      |
	| LCHIJA | cubicchunkscore    | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None      |
	| LCHIJA | cubicchunks        | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None      |
	| LCHIJA | cubicgen           | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar | None      |
	| LCHIJA | examplemod         | 1.0                        | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None      |
	| LCHIJA | flansmod           | 5.5.2                      | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None      |
	| LCHIJA | flansmodapocalypse | 1.0                        | Soviet+Flan's+Mod-1.12.2-5.5.2.1.jar            | None      |
	| LCHIJA | terra121           | 0.1.5                      | terra121-0.1.5.jar                              | None      |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 432.00, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by Joey-Destroyah** [comment]
Never mind i found the culprit. sorry for taking up your time.
