### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by Escartem** [OpenCubicChunks/CubicWorldGen#65]
The game crash every time I click on "Customize" when creating a new world, "CustomCubic" world type is selected.

Crashlog : 
`
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/23/19 7:29 PM
Description: Updating screen events

java.lang.NoSuchMethodError: net.malisis.core.client.gui.component.interaction.UITextField.setValidator(Lcom/google/common/base/Predicate;)Lnet/malisis/core/client/gui/component/interaction/UITextField;
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at io.github.opencubicchunks.cubicchunks.cubicgen.common.gui.MalisisGuiUtils.floatInput(MalisisGuiUtils.java:243)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.AdvancedTerrainShapeTab.<init>(AdvancedTerrainShapeTab.java:125)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.reinit(CustomCubicGui.java:100)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.gui.CustomCubicGui.construct(CustomCubicGui.java:92)
	at net.malisis.core.client.gui.MalisisGui.doConstruct(MalisisGui.java:150)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:705)
	at net.malisis.core.client.gui.MalisisGui.display(MalisisGui.java:694)
	at io.github.opencubicchunks.cubicchunks.cubicgen.customcubic.CustomCubicWorldType.onCustomizeButton(CustomCubicWorldType.java:104)
	at net.minecraft.client.gui.GuiCreateWorld.func_146284_a(GuiCreateWorld.java:317)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:416)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1052191240 bytes (1003 MB) / 1509949440 bytes (1440 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 8 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                   | Source                                         | Signature                                |
	|:------ |:--------------- |:------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                    | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp             | 9.42                      | minecraft.jar                                  | None                                     |
	| LCHIJA | FML             | 8.0.99.99                 | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2838              | forge-1.12.2-14.23.5.2838.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.970.0-SNAPSHOT | CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar  | None                                     |
	| LCHIJA | cubicgen        | 1.12.2-0.0.39.1-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | malisiscore     | 1.12.2-6.5.1-SNAPSHOT     | malisiscore-1.12.2-6.5.1.jar                   | None                                     |
	| UD     | cubicchunkscore | @@VERSION@@               | minecraft.jar                                  | None                                     |

	Loaded coremods (and transformers): 
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.39.1-SNAPSHOT-all.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.970.0-SNAPSHOT-all.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4010U CPU @1.70GHz
`

**Comment by BaccarWozat** [comment]
Use older MalisisCore (6.4.0) or a later CWG. Later builds of CWG are found on the discord.
